name: CI Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure backend folder exists
        run: |
          if [ ! -d backendCleanArquitecture ]; then
            mkdir backendCleanArquitecture
          fi
          # Agregar un archivo temporal para que npm funcione incluso si la carpeta está vacía
          if [ ! -f backendCleanArquitecture/placeholder.txt ]; then
            echo "Placeholder file to ensure folder exists" > backendCleanArquitecture/placeholder.txt
          fi

      - name: Debug backend folder
        run: ls -la backendCleanArquitecture

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Install backend dependencies
        run: |
          cd backendCleanArquitecture
          npm install --force

      - name: Run backend tests
        run: |
          cd backendCleanArquitecture
          npm test

      - name: Build backend
        run: |
          cd backendCleanArquitecture
          npm run build

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure frontend folder exists
        run: |
          if [ ! -d front ]; then
            mkdir front
          fi
          if [ ! -f front/placeholder.txt ]; then
            echo "Placeholder file to ensure folder exists" > front/placeholder.txt
          fi

      - name: Debug frontend folder
        run: ls -la front

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.14.0

      - name: Install frontend dependencies
        run: |
          cd front
          npm install --force

      - name: Run frontend tests
        run: |
          cd front
          npm test --if-present

      - name: Build frontend
        run: |
          cd front
          npm run build
